version: "3.9"
services:
  db:
    image: postgres:15
    container_name: monorepo_db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: mono_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  # frontend:
  #   build: ./frontend
  #   container_name: mono_frontend
  #   environment:
  #     NEXT_PUBLIC_API_URL: "http://localhost:8000"
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"

volumes:
  pgdata:
